#!/usr/bin/env node

/*global process*/

const yargs = require('yargs');

const encrypt = require('./encrypt');
const decrypt = require('./decrypt');
const sign = require('./sign');
const verify = require('./verify');
const inlineSign = require('./inlineSign');
const inlineVerify = require('./inlineVerify');
const generate = require('./generate');
const extract = require('./extract');
const openpgp = require('openpgp');

yargs
  .command({
    command: 'encrypt [certfile]',
    describe: 'Encrypt a Message',
    builder: {
      'with-password': {
        describe: 'symmetric encryption',
        type: 'string'
      },
      'sign-with': {
        describe: 'sign with key',
      },
      as: {
        describe: 'binary or text'
      }
    },
    handler: async (argv) => {
      encrypt(argv.withPassword, argv.signWith, argv.certfile);
    }
  })
  .command({
    command: 'decrypt [certfile]',
    describe: 'Decrypt a Message',
    builder: {
      'session-key-out': {
        describe: 'session key of encrypted message',
      },
      'with-session-key': {
        describe: 'decrypt using provided session key',
      },
      'with-password': {
        describe: 'symmetric encryption',
        type: 'string'
      },
      'verify-with': {
        describe: 'verify with key',
      },
      'verify-out': {
        describe: 'save verifications to file',
      }
    },
    handler: async (argv) => {
      decrypt(argv.withPassword, argv.sessionKeyOut , argv.withSessionKey, argv.verifyWith, argv.verifyOut, argv.certfile);
    }
  })
  .command({
    command: 'sign <certfile>',
    describe: 'Create Detached Signatures',
    handler: async (argv) => { sign(argv.certfile); }
  })
  .command({
    command: 'verify <signature> <certfile>',
    describe: 'Verify Detached Signatures',
    handler: async (argv) => { verify(argv.signature, argv.certfile); }
  })
  .command({
    command: 'inline-sign <certfile>',
    describe: 'Create an Inline-Signed Message',
    builder: {
      as: {
        describe: 'binary or text'
      },
      armor: {
        describe: 'armor the output',
        type: 'boolean'
      }
    },
    handler: async (argv) => {
      const armor = argv.armor != false;
      inlineSign(argv.certfile, argv.as, armor);
    }
  })
  .command({
    command: 'inline-verify <certfile>',
    describe: 'Verify an Inline-Signed Message',
    builder: {
      'verifications-out': {
        describe: 'save verifications to file',
      }
    },
    handler: async (argv) => { inlineVerify(argv.certfile, argv.verificationsOut); }
  })
  .command({
    command: 'extract-cert <certfile>',
    describe: 'Extract a Certificate from a Secret Key',
    builder: {
      armor: {
        describe: 'armor the output',
        type: 'boolean'
      }
    },
    handler: async (argv) => {
      const armor = argv.armor != false;
      extract(armor, argv.certfile);
    }
  })
  .command({
    command: 'generate-key [userids..]',
    describe: 'Generate a Secret Key',
    builder: {
      armor: {
        describe: 'armor the output',
        type: 'boolean'
      },
      userids: {
        describe: 'some user ids',
        type: 'string'
      }
    },
    handler: async (argv) => {
      const armor = argv.armor != false;
      const userids = argv.userids || [];
      generate(armor, userids);
    }
  })
  .command({
    command: 'version',
    describe: 'Version Information',
    builder: {
      backend: {
        describe: 'display OpenPGP.js version',
        type: 'boolean'
      },
      extended: {
        describe: 'display extended version information',
        type: 'boolean'
      }
    },
    handler: (argv) => {
      if (!argv.backend || argv.extended) {
        const package = require('./package.json');
        console.log(package.name + ' ' + package.version);
      }
      if (argv.backend || argv.extended) {
        console.log(openpgp.config.versionString);
      }
      if (argv.extended) {
        console.log('Running on Node.js ' + process.version);
      }
    }
  })
  .version(false) // Disable --version option as we have our own version command.
  .help()
  .alias('help', 'h')
  .demandCommand(1)
  .strict()
  .argv;
